export { runMigrations } from './migrate';
export * from './schema/users';
export * from './schema/password-reset-tokens';
export * from './schema/categories';
export * from './schema/courses';
export * from './schema/modules';
export * from './schema/lesson-resources';
export * from './schema/lessons';
export * from './schema/enrollments';
export * from './schema/lesson-progress';
export * from './schema/extra-unlock-celebrations';
export * from './schema/cohorts';
export * from './schema/platform-config';
export * from './schema/relations';
export * from './schema/oauth-clients';
export * from './schema/oauth-authorization-codes';
export * from './schema/oauth-access-tokens';
